services:
  - type: web
    name: registrar-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    disk:
      name: bot_data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DB_FILE
        value: /data/attendance.db
      - key: DISCORD_TOKEN
        sync: false
